language: node_js
node_js:
- stable
script:
- cd client
- npm ci
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: MKeUn9vBjAxG7jVLGcVffb2BYhIKhA4XGzcDgUP0NJYtvFt7UF1/AvAXKz9szVoaHFe0UYKGZKFAEEORyob/p41xauWS5nYf7xSRnOkXMivRYbJNkDdUnOjm5kvksXKz4rCmaXOq6ycc2KwIiBC+C2sJ5AYH4dH3x1k+ufG3EZvmL18b5lUZqOTMx0VjL1vwnsxYUfWZnSFMuaA6+2CnDJnHbmsoEFdtUwqktWcL9Tg3jfjQBLQ+j8uEpDbQFQRtJzHVRIUPkbvWvvn9jA01+E7klZzwl9+SYtPh8ZznOeKS4tcOqBFjYC2dJCZVrhAuU2Av6FwJmZdzm7DOGasW1hRnn87ky15ZdmmcRoQbA0JZK1Zypmo2kvLk113AhKuPG3Bnc22HaF7CHMt5kqfGJPL+hycJfLMDxZ72Ms55MYlk7N6bnBuA1WDuA64te+gDETFhlBHocXVMoCt4YvaN7BuP1QTe8n28vuDx3jSnw7ODdJ+FOpoovjuF9alaCy3va3bvdFbbqYLtKIQrt1C4GIMTZgORGVPR0PYF/17IWUO9ULIBIammG2AAbco6z6GV1f/VFyG62WvARq86Sq4txqpCIKPQFfBBf8E9uySnxQzbJnI4vy71LnpXGEjIFAGIaVZIcpGrkgh21Z22/MCfEXvt3Rb3oIfkUifiqB11HIg=
  app:
    master: cyclair
    dev: cyclair-dev
    b/invalid-h: bugfick
  skip_cleanup: true
